Fix build warnings in nptl/tst-eintr1.c
This patch fixes the gcc warnings seen with gcc 9.1 -O3 on s390x:
tst-eintr1.c: In function ‘tf1’:
tst-eintr1.c:46:1: error: no return statement in function returning non-void [-Werror=return-type]
   46 | }
      | ^
tst-eintr1.c: In function ‘do_test’:
tst-eintr1.c:57:17: error: unused variable ‘th’ [-Werror=unused-variable]
   57 |       pthread_t th = xpthread_create (NULL, tf1, NULL);
      |                 ^~

ChangeLog:

	* nptl/tst-eintr1.c (tf1): Add return statement.
	(do_test): Remove unused th variable.